//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingOTPs
    {
        public int OTPId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string OTP { get; set; }
        public System.DateTime GeneratedAt { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Users Users { get; set; }
    }
}
